# junction_cnn/constants.py

IMAGE_WIDTH = 512
IMAGE_HEIGHT = 512
NUM_JUNCTIONS = 50
VALIDATION_SIZE = 50
NUM_WORKERS = 4

# Direction Configuration
NUM_DIRECTION_BINS = 72
DIRECTION_ANGLE_STEP = 360.0 / NUM_DIRECTION_BINS

# Prediction & Decoding Hyperparameters
JUNCTION_THRESHOLD = 0.4
DIRECTION_THRESHOLD = 0.3
JUNCTION_NMS_RADIUS = 4
JUNCTION_TOLERANCE = 5.0
JUNCTION_MERGE_DISTANCE = 5.0
DIRECTION_TOLERANCE = 10.0
DIRECTION_NMS_DEGREES = 10.0
DIRECTION_RADIUS = 4

# Overlay Visualization Defaults
OVERLAY_LINE_LENGTH = 25
OVERLAY_LINE_WIDTH = 2
OVERLAY_JUNCTION_RADIUS = 4
OVERLAY_FADE = 0.35

# Training Hyperparameters
WEIGHT_DECAY = 1e-4
GRADIENT_CLIP = 5.0